### ISSUE TITLE
Mismatch of number of parameters 

### ISSUE THREAD

**Issue by kabbas570** [jankrepl/mildlyoverfitted#18]
Hey, the number of parameters in your custom model are not matching with nay of the model here?

https://pytorch.org/vision/stable/models/vision_transformer.html

**Comment by jankrepl** [comment]
> Hey, the number of parameters in your custom model are not matching with nay of the model here?
> 
> https://pytorch.org/vision/stable/models/vision_transformer.html

I have never used `torch-vision` ViT models before so cannot really tell you why that is the case without without inspecting things in detail. The video is based on `timm`.

Anyway, I suggest you go module by module and find the first one where the # parameters disagree. It will most likely be related to some different hyperparameter

**Comment by jankrepl** [comment]
> Hey there @jankrepl (yes I'm trolling) I miss your YouTube videos! Hope you are planning to do another one soon! I hear there's this new thing called Stable Diffusion...

@vgoklani Hehe:) Thanks, I got a bit lazy recently. I will try to go back to more frequent uploads:)
